apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.selectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "app.selectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      name: http
