api:
  insecure: true

providers:
  docker:
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

certificatesResolvers:
  letsencryptresolver:
    acme:
      email: aliriza.esenli@hotmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
