apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: user-mgmt
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/userdb"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  JWT_ISSUER: "user-mgmt-service"
  JWT_EXPIRATION_MILLIS: "3600000"
